service: tech-writer

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  stage: dev

package:
 exclude:
   - ./**
 include:
   - ./bin/**

plugins:
  - serverless-sam

functions:
  articles_index:
    handler: bin/articles_index
    events:
      - http:
          path: /articles
          method: get
          cors: true
  articles_create:
    handler: bin/articles_create
    events:
      - http:
          path: /articles
          method: post
          cors: true
  articles_show:
    handler: bin/articles_show
    events:
      - http:
          path: /articles/{id}
          method: get
          cors: true
  articles_update:
    handler: bin/articles_update
    events:
      - http:
          path: /articles/{id}
          method: post
          cors: true
  articles_destroy:
    handler: bin/articles_destroy
    events:
      - http:
          path: /articles/{id}
          method: delete
          cors: true
