build:
	env GOOS=linux go build -ldflags="-s -w" -o bin/articles_index src/github.com/vleango/articles/index.go
	env GOOS=linux go build -ldflags="-s -w" -o bin/articles_create src/github.com/vleango/articles/create.go
	env GOOS=linux go build -ldflags="-s -w" -o bin/articles_show src/github.com/vleango/articles/show.go
	env GOOS=linux go build -ldflags="-s -w" -o bin/articles_update src/github.com/vleango/articles/update.go
	env GOOS=linux go build -ldflags="-s -w" -o bin/articles_destroy src/github.com/vleango/articles/destroy.go
