build:
	env GOOS=linux go build -ldflags="-s -w" -o bin/articles_get_index src/github.com/vleango/articles/index.go
	env GOOS=linux go build -ldflags="-s -w" -o bin/articles_get_show src/github.com/vleango/articles/show.go
