AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: '
Resources:
  Articles_index:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: bin/articles_index
      Runtime: go1.x
      CodeUri: /go/src/github.com/vleango/.serverless/tech-writer.zip
      MemorySize: 128
      Timeout: 3
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /articles
            Method: get
            RestApiId:
              Ref: TechWriter
  TechWriter:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        info:
          title:
            Ref: 'AWS::StackName'
        paths:
          /articles:
            options:
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: '{ "statusCode" : 200 }'
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''options,get,post'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}'
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Articles_index.Arn}/invocations
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''get'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}'
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Articles_create.Arn}/invocations
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''options,get,post'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}'
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
          '/articles/{id}':
            options:
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: '{ "statusCode" : 200 }'
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''options,get,post,delete'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}'
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Articles_show.Arn}/invocations
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''get'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}'
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Articles_update.Arn}/invocations
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''options,get,post'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}'
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
            delete:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Articles_destroy.Arn}/invocations
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''options,get,post,delete'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}'
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
  Articles_indexLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - Articles_index
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: Articles_index
      Principal: apigateway.amazonaws.com
  Articles_create:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: bin/articles_create
      Runtime: go1.x
      CodeUri: /go/src/github.com/vleango/.serverless/tech-writer.zip
      MemorySize: 128
      Timeout: 3
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /articles
            Method: post
            RestApiId:
              Ref: TechWriter
  Articles_createLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - Articles_create
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: Articles_create
      Principal: apigateway.amazonaws.com
  Articles_show:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: bin/articles_show
      Runtime: go1.x
      CodeUri: /go/src/github.com/vleango/.serverless/tech-writer.zip
      MemorySize: 128
      Timeout: 3
      Events:
        Event1:
          Type: Api
          Properties:
            Path: '/articles/{id}'
            Method: get
            RestApiId:
              Ref: TechWriter
  Articles_showLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - Articles_show
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: Articles_show
      Principal: apigateway.amazonaws.com
  Articles_update:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: bin/articles_update
      Runtime: go1.x
      CodeUri: /go/src/github.com/vleango/.serverless/tech-writer.zip
      MemorySize: 128
      Timeout: 3
      Events:
        Event1:
          Type: Api
          Properties:
            Path: '/articles/{id}'
            Method: post
            RestApiId:
              Ref: TechWriter
  Articles_updateLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - Articles_update
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: Articles_update
      Principal: apigateway.amazonaws.com
  Articles_destroy:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: bin/articles_destroy
      Runtime: go1.x
      CodeUri: /go/src/github.com/vleango/.serverless/tech-writer.zip
      MemorySize: 128
      Timeout: 3
      Events:
        Event1:
          Type: Api
          Properties:
            Path: '/articles/{id}'
            Method: delete
            RestApiId:
              Ref: TechWriter
        Event2:
          Type: Api
          Properties:
            Path: '/articles/{id}'
            Method: options
            RestApiId:
              Ref: TechWriter
  Articles_destroyLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - Articles_destroy
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: Articles_destroy
      Principal: apigateway.amazonaws.com
